In [1]:
import torch
import pandas as pd

from tqdm.notebook import trange, tqdm

In [2]:
for i in trange(10):
    print(i)

  0%|          | 0/10 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9


In [3]:
torch.cuda.is_available()

True

In [4]:
path = "C:/Users/agraw/project/Bloom_taxonomy_dataset_english.csv"
df = pd.read_csv(path, names = ["Class", "Questions"])

In [5]:
df.head()

Class                                          Questions
0  Knowledge  About what proportion of the population of the...
1  Knowledge  Correctly label the brain lobes indicated on t...
2  Knowledge                          Define compound interest.
3  Knowledge                 Define four types of traceability.
4  Knowledge                               Define mercantilism.

In [6]:
df.Class.value_counts()

Analysis         100
Synthesis        100
Comprehension    100
Application      100
Knowledge        100
Evaluation       100
Name: Class, dtype: int64

In [7]:
possible_labels = df.Class.unique()

In [8]:
from googletrans import Translator

In [9]:
translator = Translator()

In [13]:
df['Class'] = df['Class'].apply(translator.translate, src='en', dest='hi').apply(getattr, args=('text',))

In [14]:
df.Class.value_counts()

ज्ञान        100
समझ          100
संश्लेषण     100
आवेदन        100
विश्लेषण     100
मूल्यांकन    100
Name: Class, dtype: int64

In [15]:
df['Questions'] = df['Questions'].apply(translator.translate, src='en', dest='hi').apply(getattr, args=('text',))

In [16]:
df.head()

Class                                          Questions
0  ज्ञान  खेतों पर अमेरिका की आबादी का अनुपात किस बारे म...
1  ज्ञान  नीचे दिए गए आरेख पर संकेतित मस्तिष्क लोब को सह...
2  ज्ञान                      यौगिक ब्याज को परिभाषित करें।
3  ज्ञान       चार प्रकार की ट्रेसिबिलिटी को परिभाषित करें।
4  ज्ञान                    मर्केंटिलिज्म को परिभाषित करें।

In [17]:
df.to_csv('Bloom_taxonomy_dataset_hindi.csv')

In [10]:
path = "C:/Users/agraw/project/Bloom_taxonomy_dataset_hindi.csv"
df = pd.read_csv(path, names = ["Class", "Questions"])

In [11]:
df.head()

Class                                          Questions
0  ज्ञान  खेतों पर अमेरिका की आबादी का अनुपात किस बारे म...
1  ज्ञान  नीचे दिए गए आरेख पर संकेतित मस्तिष्क लोब को सह...
2  ज्ञान                      यौगिक ब्याज को परिभाषित करें।
3  ज्ञान       चार प्रकार की ट्रेसिबिलिटी को परिभाषित करें।
4  ज्ञान                    मर्केंटिलिज्म को परिभाषित करें।

In [12]:
possible_labels = df.Class.unique()

In [13]:
label_dict = {}
for index, possible_label in enumerate(possible_labels):
    label_dict[possible_label] = index

In [14]:
label_dict

{'ज्ञान': 0,
 'समझ': 1,
 'आवेदन': 2,
 'विश्लेषण': 3,
 'संश्लेषण': 4,
 'मूल्यांकन': 5}

In [15]:
df['label'] = df.Class.replace(label_dict)
df.head()

Class                                          Questions  label
0  ज्ञान  खेतों पर अमेरिका की आबादी का अनुपात किस बारे म...      0
1  ज्ञान  नीचे दिए गए आरेख पर संकेतित मस्तिष्क लोब को सह...      0
2  ज्ञान                      यौगिक ब्याज को परिभाषित करें।      0
3  ज्ञान       चार प्रकार की ट्रेसिबिलिटी को परिभाषित करें।      0
4  ज्ञान                    मर्केंटिलिज्म को परिभाषित करें।      0

In [16]:
df['Questions'].iloc[0]

'खेतों पर अमेरिका की आबादी का अनुपात किस बारे में है?'

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
df.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [19]:
df.label.values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,

In [20]:
X_train, X_val, y_train, y_val = train_test_split(df.index.values, df.label.values, test_size = 0.20, random_state = 20, stratify = df.label.values)

In [21]:
X_train

array([311, 255, 445, 135, 413, 546, 171, 513, 405,   8, 469, 474, 155,
        14, 280, 436, 240, 214, 376, 500, 351, 326,  67, 119,  47,  18,
       529, 403, 104, 111,   6, 167, 532, 371, 112, 133, 145, 110, 106,
       486, 525, 440, 584, 459, 465, 542, 225, 180,  80, 530, 140, 514,
       176, 303, 595, 433,  93, 356, 314, 192, 290, 342,  54,  92, 191,
       437, 345,  41,  87, 128, 248, 470, 277, 243, 182,  38, 273, 101,
       410, 483, 419, 434,  60, 181,  69, 247, 208, 579, 161,  37, 493,
       430, 471, 251,  30, 286, 431,  25, 573, 230, 429,  51, 183, 558,
       497, 132,  24, 505, 504, 451, 328,  12, 186, 346, 416, 333, 329,
       364,   5, 200, 586, 378,  44, 254, 519, 115, 522, 324,  29, 563,
       556, 457, 120, 583, 307, 188, 454,  94, 172,  72, 195, 332, 292,
        43,  53,  76, 580, 362, 147, 334, 396, 400, 506, 317, 432, 103,
       338, 159, 146, 509,  59, 184, 408, 368,  10, 567, 198, 478, 339,
       142, 393, 464,  46,  79,  35, 370, 541, 170, 148, 390, 23

In [22]:
y_train

array([3, 2, 4, 1, 4, 5, 1, 5, 4, 0, 4, 4, 1, 0, 2, 4, 2, 2, 3, 5, 3, 3,
       0, 1, 0, 0, 5, 4, 1, 1, 0, 1, 5, 3, 1, 1, 1, 1, 1, 4, 5, 4, 5, 4,
       4, 5, 2, 1, 0, 5, 1, 5, 1, 3, 5, 4, 0, 3, 3, 1, 2, 3, 0, 0, 1, 4,
       3, 0, 0, 1, 2, 4, 2, 2, 1, 0, 2, 1, 4, 4, 4, 4, 0, 1, 0, 2, 2, 5,
       1, 0, 4, 4, 4, 2, 0, 2, 4, 0, 5, 2, 4, 0, 1, 5, 4, 1, 0, 5, 5, 4,
       3, 0, 1, 3, 4, 3, 3, 3, 0, 2, 5, 3, 0, 2, 5, 1, 5, 3, 0, 5, 5, 4,
       1, 5, 3, 1, 4, 0, 1, 0, 1, 3, 2, 0, 0, 0, 5, 3, 1, 3, 3, 4, 5, 3,
       4, 1, 3, 1, 1, 5, 0, 1, 4, 3, 0, 5, 1, 4, 3, 1, 3, 4, 0, 0, 0, 3,
       5, 1, 1, 3, 2, 5, 3, 4, 0, 4, 5, 2, 2, 4, 4, 1, 2, 3, 4, 5, 1, 1,
       4, 2, 0, 3, 2, 1, 5, 2, 0, 2, 2, 2, 4, 1, 4, 3, 0, 3, 3, 0, 2, 2,
       4, 5, 3, 0, 0, 1, 3, 2, 5, 0, 3, 3, 3, 2, 3, 2, 5, 3, 2, 4, 2, 1,
       0, 1, 5, 5, 2, 2, 3, 1, 5, 2, 2, 1, 4, 0, 0, 5, 5, 2, 1, 3, 2, 2,
       4, 1, 1, 3, 2, 0, 3, 5, 3, 3, 4, 2, 5, 2, 1, 5, 2, 4, 1, 0, 1, 1,
       5, 4, 2, 5, 3, 1, 1, 5, 4, 3, 3, 1, 5, 5, 1,

In [23]:
df['data_type'] = ['no_set']*df.shape[0]

In [24]:
X_train

array([311, 255, 445, 135, 413, 546, 171, 513, 405,   8, 469, 474, 155,
        14, 280, 436, 240, 214, 376, 500, 351, 326,  67, 119,  47,  18,
       529, 403, 104, 111,   6, 167, 532, 371, 112, 133, 145, 110, 106,
       486, 525, 440, 584, 459, 465, 542, 225, 180,  80, 530, 140, 514,
       176, 303, 595, 433,  93, 356, 314, 192, 290, 342,  54,  92, 191,
       437, 345,  41,  87, 128, 248, 470, 277, 243, 182,  38, 273, 101,
       410, 483, 419, 434,  60, 181,  69, 247, 208, 579, 161,  37, 493,
       430, 471, 251,  30, 286, 431,  25, 573, 230, 429,  51, 183, 558,
       497, 132,  24, 505, 504, 451, 328,  12, 186, 346, 416, 333, 329,
       364,   5, 200, 586, 378,  44, 254, 519, 115, 522, 324,  29, 563,
       556, 457, 120, 583, 307, 188, 454,  94, 172,  72, 195, 332, 292,
        43,  53,  76, 580, 362, 147, 334, 396, 400, 506, 317, 432, 103,
       338, 159, 146, 509,  59, 184, 408, 368,  10, 567, 198, 478, 339,
       142, 393, 464,  46,  79,  35, 370, 541, 170, 148, 390, 23

In [25]:
df.loc[X_train, 'data_type'] = 'train'
df.loc[X_val, 'data_type'] = 'val'

In [26]:
df.groupby(['Class', 'label', 'data_type']).count()

Questions
Class     label data_type           
आवेदन     2     train             80
                val               20
ज्ञान     0     train             80
                val               20
मूल्यांकन 5     train             80
                val               20
विश्लेषण  3     train             80
                val               20
संश्लेषण  4     train             80
                val               20
समझ       1     train             80
                val               20

In [27]:
from transformers import BertTokenizer, AutoModel, AutoTokenizer
from torch.utils.data import TensorDataset

In [28]:
#tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case = True)
tokenizer = AutoTokenizer.from_pretrained('ai4bharat/indic-bert')

In [29]:
df.data_type == 'train'

0      True
1      True
2      True
3      True
4      True
       ... 
595    True
596    True
597    True
598    True
599    True
Name: data_type, Length: 600, dtype: bool

In [30]:
df[df.data_type == 'train']

Class                                          Questions  label  \
0        ज्ञान  खेतों पर अमेरिका की आबादी का अनुपात किस बारे म...      0   
1        ज्ञान  नीचे दिए गए आरेख पर संकेतित मस्तिष्क लोब को सह...      0   
2        ज्ञान                      यौगिक ब्याज को परिभाषित करें।      0   
3        ज्ञान       चार प्रकार की ट्रेसिबिलिटी को परिभाषित करें।      0   
4        ज्ञान                    मर्केंटिलिज्म को परिभाषित करें।      0   
..         ...                                                ...    ...   
595  मूल्यांकन            आपको क्या लगता है कि द्रव्यमान और क्यों      5   
596  मूल्यांकन  आप अपने कार्यक्रम में एकीकृत गणित का उपयोग करन...      5   
597  मूल्यांकन  क्या आपको लगता है कि यह कथन इस विचार को व्यक्त...      5   
598  मूल्यांकन  आपको कैसे लगता है कि समुदाय को बढ़ना या बदलना ...      5   
599  मूल्यांकन  आपको लगता है कि किसी को व्यवसाय में नैतिक निर्...      5   

    data_type  
0       train  
1       train  
2       train  
3       train  
4       train  
..        ...  
595     train  
596     train  
597     train  
598     train  
599     train  

[480 rows x 4 columns]

In [31]:
df[df.data_type == 'train'].Questions.values

array(['खेतों पर अमेरिका की आबादी का अनुपात किस बारे में है?',
       'नीचे दिए गए आरेख पर संकेतित मस्तिष्क लोब को सही ढंग से लेबल करें',
       'यौगिक ब्याज को परिभाषित करें।',
       'चार प्रकार की ट्रेसिबिलिटी को परिभाषित करें।',
       'मर्केंटिलिज्म को परिभाषित करें।',
       'स्ट्रीम बैंक, बाढ़ के मैदान और सब्सट्रेट को परिभाषित करें।',
       'ओलंपिक आदर्श वाक्य का अर्थ परिभाषित करें।',
       'कॉर्नेल विधि का उपयोग करके नोट्स के पृष्ठ की मूल रूपरेखा बनाएं?',
       'पीएनके सिस्टम का प्रवाह चार्ट बनाएं',
       'एक आरआईएससी कंप्यूटर के निर्देश सेट में कितने निर्देश हैं?',
       'आपके घर से विश्वविद्यालय में कितने किलोमीटर तक',
       'सी ++ में कितने लूप स्टेटमेंट उपलब्ध हैं?',
       'संयुक्त राज्य अमेरिका में कितने राज्य हैं',
       'उसने अपनी कार के लिए कितना भुगतान किया', 'आपका वजन कितना है',
       'एक घर बनाने में कितना समय लगा',
       'एक अनुकरण के रूप में एक वाक्यांश की पहचान करें',
       'एक चित्रमय प्रतिनिधित्व से भिन्नताओं की पहचान करें',
       'क्रमिक पदों की पहच

In [32]:
df[df.data_type == 'train'].Questions.values.tolist()

['खेतों पर अमेरिका की आबादी का अनुपात किस बारे में है?',
 'नीचे दिए गए आरेख पर संकेतित मस्तिष्क लोब को सही ढंग से लेबल करें',
 'यौगिक ब्याज को परिभाषित करें।',
 'चार प्रकार की ट्रेसिबिलिटी को परिभाषित करें।',
 'मर्केंटिलिज्म को परिभाषित करें।',
 'स्ट्रीम बैंक, बाढ़ के मैदान और सब्सट्रेट को परिभाषित करें।',
 'ओलंपिक आदर्श वाक्य का अर्थ परिभाषित करें।',
 'कॉर्नेल विधि का उपयोग करके नोट्स के पृष्ठ की मूल रूपरेखा बनाएं?',
 'पीएनके सिस्टम का प्रवाह चार्ट बनाएं',
 'एक आरआईएससी कंप्यूटर के निर्देश सेट में कितने निर्देश हैं?',
 'आपके घर से विश्वविद्यालय में कितने किलोमीटर तक',
 'सी ++ में कितने लूप स्टेटमेंट उपलब्ध हैं?',
 'संयुक्त राज्य अमेरिका में कितने राज्य हैं',
 'उसने अपनी कार के लिए कितना भुगतान किया',
 'आपका वजन कितना है',
 'एक घर बनाने में कितना समय लगा',
 'एक अनुकरण के रूप में एक वाक्यांश की पहचान करें',
 'एक चित्रमय प्रतिनिधित्व से भिन्नताओं की पहचान करें',
 'क्रमिक पदों की पहचान करें',
 'ऑस्मोसिस की सही परिभाषा को पहचानें।',
 'एक यूकेरियोटिक सेल के हिस्से की पहचान करें।',
 'पहचानें

In [33]:
encoded_data_train = tokenizer.batch_encode_plus(
    df[df.data_type == 'train'].Questions.values.tolist(),
    add_special_tokens = True,
    return_attention_mask = True,
    padding = True,
    truncation = True,
    max_length = 256,
    return_tensors = 'pt'
)

In [34]:
encoded_data_train

{'input_ids': tensor([[    2, 25809,    37,  ...,     0,     0,     0],
        [    2,   236,   232,  ...,     0,     0,     0],
        [    2,  5478,  2389,  ...,     0,     0,     0],
        ...,
        [    2,  1883,  1134,  ...,     0,     0,     0],
        [    2,   344,   507,  ...,     0,     0,     0],
        [    2,   344,   507,  ...,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [35]:
encoded_data_val = tokenizer.batch_encode_plus(
    df[df.data_type == 'val'].Questions.values.tolist(),
    add_special_tokens = True,
    return_attention_mask = True,
    padding = True,
    truncation = True,
    max_length = 256,
    return_tensors = 'pt'
)

In [36]:
encoded_data_val

{'input_ids': tensor([[    2,    45, 27258,  ...,     0,     0,     0],
        [    2, 57597,  1134,  ...,     0,     0,     0],
        [    2,   114,  3121,  ...,     0,     0,     0],
        ...,
        [    2,  1883,  1134,  ...,     0,     0,     0],
        [    2, 25397,  1976,  ...,     0,     0,     0],
        [    2,  1301, 13700,  ...,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [37]:
input_ids_train = encoded_data_train['input_ids']
attention_masks_train = encoded_data_train['attention_mask']
labels_train = torch.tensor(df[df.data_type == 'train'].label.values)

In [38]:
input_ids_val = encoded_data_val['input_ids']
attention_masks_val = encoded_data_val['attention_mask']
labels_val = torch.tensor(df[df.data_type == 'val'].label.values)

In [39]:
dataset_train = TensorDataset(
    input_ids_train,
    attention_masks_train,
    labels_train
)

In [40]:
dataset_val = TensorDataset(
    input_ids_val,
    attention_masks_val,
    labels_val
)

In [41]:
len(dataset_train)

480

In [42]:
len(dataset_val)

120

In [43]:
from transformers import BertForSequenceClassification

In [44]:
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', 
                                                     num_labels = len(label_dict), 
                                                     output_attentions = False, 
                                                     output_hidden_states = False)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [40]:
model = AutoModel.from_pretrained('ai4bharat/indic-bert')

Some weights of the model checkpoint at ai4bharat/indic-bert were not used when initializing AlbertModel: ['predictions.decoder.weight', 'predictions.dense.bias', 'predictions.LayerNorm.bias', 'sop_classifier.classifier.weight', 'predictions.decoder.bias', 'predictions.LayerNorm.weight', 'predictions.bias', 'predictions.dense.weight', 'sop_classifier.classifier.bias']
- This IS expected if you are initializing AlbertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [45]:
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler

In [46]:
batch_size = 4
dataloader_train = DataLoader(
    dataset_train,
    sampler = RandomSampler(dataset_train), 
    batch_size = batch_size
)

dataloader_val = DataLoader(
    dataset_val, 
    sampler = RandomSampler(dataset_val), 
    batch_size = batch_size)

In [47]:
from transformers import AdamW, get_linear_schedule_with_warmup

In [48]:
optimizer = AdamW(
    model.parameters(), 
    lr = 1e-5, 
    eps = 1e-8)

In [49]:
epochs = 10

scheduler = get_linear_schedule_with_warmup(
    optimizer, 
    num_warmup_steps = 0, 
    num_training_steps = len(dataloader_train) * epochs
)

In [50]:
import numpy as np

In [51]:
from sklearn.metrics import f1_score

In [52]:
def f1_score_func(preds, labels):
    preds_flat = np.argmax(preds, axis = 1).flatten()
    labels_flat = labels.flatten()
    return f1_score(labels_flat, preds_flat, average = 'weighted')

In [53]:
def accuracy_per_class(preds, labels):
    label_dict_inverse = {v: k for k, v in label_dict.items()}
    preds_flat = np.argmax(preds, axis = 1).flatten()
    labels_flat = labels.flatten()
    
    for label in np.unique(labels_flat):
        y_pred = preds_flat[labels_flat == label]
        y_true = labels_flat[labels_flat == label]
        print(f'Class: {label_dict_inverse[label]}')
        print(f'Accuracy: {len(y_pred[y_pred == label])} / {len(y_true)}\n')

In [54]:
import random

seed_val = 20
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

In [55]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)
print(device)

cuda


In [56]:
def evaluate(dataloader_val):
    model.eval()
    loss_val_total = 0
    predictions, true_vals = [], []
    for batch in tqdm(dataloader_val):
        batch = tuple(b.to(device) for b in batch)
        inputs = {'input_ids': batch[0],
                  'attention_mask': batch[1],
                  'labels': batch[2],
                 }
        with torch.no_grad():
            outputs = model(**inputs)
            
        loss = outputs[0]
        logits = outputs[1]
        loss_val_total += loss.item()
        
        logits = logits.detach().cpu().numpy()
        label_ids = inputs['labels'].cpu().numpy()
        predictions.append(logits)
        true_vals.append(label_ids)
        
    loss_val_avg = loss_val_total / len(dataloader_val)
    
    predictions = np.concatenate(predictions, axis = 0)
    true_vals = np.concatenate(true_vals, axis = 0)
    
    return loss_val_avg, predictions, true_vals

In [57]:
for epoch in tqdm(range(1, epochs + 1)):
    
    model.train()
    
    loss_train_total = 0
    
    progress_bar = tqdm(dataloader_train,
                        desc = 'Epoch {:1d}'.format(epoch),
                        leave = False,
                        disable = False)
    
    for batch in progress_bar:
        model.zero_grad()
        batch = tuple(b.to(device) for b in batch)
        inputs = {
            'input_ids': batch[0], 
            'attention_mask': batch[1], 
            'labels': batch[2]
        }
        
        outputs = model(**inputs)
        loss = outputs[0]
        loss_train_total += loss.item()
        loss.backward()
        
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        progress_bar.set_postfix(
            {'training_loss': '{:.3f}'.format(loss.item() / len(batch))})
        
    tqdm.write('\nEpoch {epoch}')
    
    loss_train_avg = loss_train_total / len(dataloader_train)
    tqdm.write(f'Training loss: {loss_train_avg}')
    
    val_loss, predictions, true_vals = evaluate(dataloader_val)
    val_f1 = f1_score_func(predictions, true_vals)
    tqdm.write(f'Validation: {val_loss}')
    tqdm.write(f'F1 Score (weighted): {val_f1}')

  0%|          | 0/10 [00:00<?, ?it/s]

Epoch 1:   0%|          | 0/120 [00:00<?, ?it/s]

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

In [51]:
torch.save(model.state_dict(), f'C:/Users/agraw/project/BERT_ft_epoch{epoch}.model')

In [52]:
model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased", 
    num_labels = len(label_dict), 
    output_attentions = False, 
    output_hidden_states = False)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [53]:
len(label_dict)

6

In [54]:
device = torch.device('cuda')
pass

In [55]:
model.to(device)
pass

In [56]:
PATH = 'C:/Users/agraw/project/BERT_ft_epoch10.model'

In [57]:
model.load_state_dict(torch.load(PATH, map_location = torch.device('cuda:0')))

<All keys matched successfully>

In [58]:
_, predictions, true_vals = evaluate(dataloader_val)

  0%|          | 0/15 [00:00<?, ?it/s]

In [59]:
accuracy_per_class(predictions, true_vals)

Class: Knowledge
Accuracy: 10 / 10

Class: Comprehension
Accuracy: 9 / 10

Class: Application
Accuracy: 8 / 10

Class: Analysis
Accuracy: 9 / 10

Class: Synthesis
Accuracy: 8 / 10

Class: Evaluation
Accuracy: 7 / 10

